<?php

namespace App\Models\Enums;

use App\Models\Enums\Enumerate;

class FacebookCustomEventTypeEnum extends Enumerate
{
    const RATE = 'RATE';
    const TUTORIAL_COMPLETION = 'TUTORIAL_COMPLETION';
    const CONTACT = 'CONTACT';
    const CUSTOMIZE_PRODUCT = 'CUSTOMIZE_PRODUCT';
    const DONATE = 'DONATE';
    const FIND_LOCATION = 'FIND_LOCATION';
    const SCHEDULE = 'SCHEDULE';
    const START_TRIAL = 'START_TRIAL';
    const SUBMIT_APPLICATION = 'SUBMIT_APPLICATION';
    const SUBSCRIBE = 'SUBSCRIBE';
    const ADD_TO_CART = 'ADD_TO_CART';
    const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
    const INITIATED_CHECKOUT = 'INITIATED_CHECKOUT';
    const ADD_PAYMENT_INFO = 'ADD_PAYMENT_INFO';
    const PURCHASE = 'PURCHASE';
    const LEAD = 'LEAD';
    const COMPLETE_REGISTRATION = 'COMPLETE_REGISTRATION';
    const CONTENT_VIEW = 'CONTENT_VIEW';
    const SEARCH = 'SEARCH';
    const SERVICE_BOOKING_REQUEST = 'SERVICE_BOOKING_REQUEST';
    const MESSAGING_CONVERSATION_STARTED_7D = 'MESSAGING_CONVERSATION_STARTED_7D';
    const LEVEL_ACHIEVED = 'LEVEL_ACHIEVED';
    const ACHIEVEMENT_UNLOCKED = 'ACHIEVEMENT_UNLOCKED';
    const SPENT_CREDITS = 'SPENT_CREDITS';
    const LISTING_INTERACTION = 'LISTING_INTERACTION';
    const D2_RETENTION = 'D2_RETENTION';
    const D7_RETENTION = 'D7_RETENTION';
    const OTHER = 'OTHER';
}
