<?php

namespace App\Models\Enums;

/**
 * @method static TZ_UNKNOWN
 * @method static TZ_AMERICA_LOS_ANGELES
 * @method static TZ_AMERICA_DENVER
 * @method static TZ_PACIFIC_HONOLULU
 * @method static TZ_AMERICA_ANCHORAGE
 * @method static TZ_AMERICA_PHOENIX
 * @method static TZ_AMERICA_CHICAGO
 * @method static TZ_AMERICA_NEW_YORK
 * @method static TZ_ASIA_DUBAI
 * @method static TZ_AMERICA_ARGENTINA_SAN_LUIS
 * @method static TZ_AMERICA_ARGENTINA_BUENOS_AIRES
 * @method static TZ_AMERICA_ARGENTINA_SALTA
 * @method static TZ_EUROPE_VIENNA
 * @method static TZ_AUSTRALIA_PERTH
 * @method static TZ_AUSTRALIA_BROKEN_HILL
 * @method static TZ_AUSTRALIA_SYDNEY
 * @method static TZ_EUROPE_SARAJEVO
 * @method static TZ_ASIA_DHAKA
 * @method static TZ_EUROPE_BRUSSELS
 * @method static TZ_EUROPE_SOFIA
 * @method static TZ_ASIA_BAHRAIN
 * @method static TZ_AMERICA_LA_PAZ
 * @method static TZ_AMERICA_NORONHA
 * @method static TZ_AMERICA_CAMPO_GRANDE
 * @method static TZ_AMERICA_BELEM
 * @method static TZ_AMERICA_SAO_PAULO
 * @method static TZ_AMERICA_NASSAU
 * @method static TZ_AMERICA_DAWSON
 * @method static TZ_AMERICA_VANCOUVER
 * @method static TZ_AMERICA_DAWSON_CREEK
 * @method static TZ_AMERICA_EDMONTON
 * @method static TZ_AMERICA_RAINY_RIVER
 * @method static TZ_AMERICA_REGINA
 * @method static TZ_AMERICA_ATIKOKAN
 * @method static TZ_AMERICA_IQALUIT
 * @method static TZ_AMERICA_TORONTO
 * @method static TZ_AMERICA_BLANC_SABLON
 * @method static TZ_AMERICA_HALIFAX
 * @method static TZ_AMERICA_ST_JOHNS
 * @method static TZ_EUROPE_ZURICH
 * @method static TZ_PACIFIC_EASTER
 * @method static TZ_AMERICA_SANTIAGO
 * @method static TZ_ASIA_SHANGHAI
 * @method static TZ_AMERICA_BOGOTA
 * @method static TZ_AMERICA_COSTA_RICA
 * @method static TZ_ASIA_NICOSIA
 * @method static TZ_EUROPE_PRAGUE
 * @method static TZ_EUROPE_BERLIN
 * @method static TZ_EUROPE_COPENHAGEN
 * @method static TZ_AMERICA_SANTO_DOMINGO
 * @method static TZ_PACIFIC_GALAPAGOS
 * @method static TZ_AMERICA_GUAYAQUIL
 * @method static TZ_EUROPE_TALLINN
 * @method static TZ_AFRICA_CAIRO
 * @method static TZ_ATLANTIC_CANARY
 * @method static TZ_EUROPE_MADRID
 * @method static TZ_EUROPE_HELSINKI
 * @method static TZ_EUROPE_PARIS
 * @method static TZ_EUROPE_LONDON
 * @method static TZ_AFRICA_ACCRA
 * @method static TZ_EUROPE_ATHENS
 * @method static TZ_AMERICA_GUATEMALA
 * @method static TZ_ASIA_HONG_KONG
 * @method static TZ_AMERICA_TEGUCIGALPA
 * @method static TZ_EUROPE_ZAGREB
 * @method static TZ_EUROPE_BUDAPEST
 * @method static TZ_ASIA_JAKARTA
 * @method static TZ_ASIA_MAKASSAR
 * @method static TZ_ASIA_JAYAPURA
 * @method static TZ_EUROPE_DUBLIN
 * @method static TZ_ASIA_JERUSALEM
 * @method static TZ_ASIA_KOLKATA
 * @method static TZ_ASIA_BAGHDAD
 * @method static TZ_ATLANTIC_REYKJAVIK
 * @method static TZ_EUROPE_ROME
 * @method static TZ_AMERICA_JAMAICA
 * @method static TZ_ASIA_AMMAN
 * @method static TZ_ASIA_TOKYO
 * @method static TZ_AFRICA_NAIROBI
 * @method static TZ_ASIA_SEOUL
 * @method static TZ_ASIA_KUWAIT
 * @method static TZ_ASIA_BEIRUT
 * @method static TZ_ASIA_COLOMBO
 * @method static TZ_EUROPE_VILNIUS
 * @method static TZ_EUROPE_LUXEMBOURG
 * @method static TZ_EUROPE_RIGA
 * @method static TZ_AFRICA_CASABLANCA
 * @method static TZ_EUROPE_SKOPJE
 * @method static TZ_EUROPE_MALTA
 * @method static TZ_INDIAN_MAURITIUS
 * @method static TZ_INDIAN_MALDIVES
 * @method static TZ_AMERICA_TIJUANA
 * @method static TZ_AMERICA_HERMOSILLO
 * @method static TZ_AMERICA_MAZATLAN
 * @method static TZ_AMERICA_MEXICO_CITY
 * @method static TZ_ASIA_KUALA_LUMPUR
 * @method static TZ_AFRICA_LAGOS
 * @method static TZ_AMERICA_MANAGUA
 * @method static TZ_EUROPE_AMSTERDAM
 * @method static TZ_EUROPE_OSLO
 * @method static TZ_PACIFIC_AUCKLAND
 * @method static TZ_ASIA_MUSCAT
 * @method static TZ_AMERICA_PANAMA
 * @method static TZ_AMERICA_LIMA
 * @method static TZ_ASIA_MANILA
 * @method static TZ_ASIA_KARACHI
 * @method static TZ_EUROPE_WARSAW
 * @method static TZ_AMERICA_PUERTO_RICO
 * @method static TZ_ASIA_GAZA
 * @method static TZ_ATLANTIC_AZORES
 * @method static TZ_EUROPE_LISBON
 * @method static TZ_AMERICA_ASUNCION
 * @method static TZ_ASIA_QATAR
 * @method static TZ_EUROPE_BUCHAREST
 * @method static TZ_EUROPE_BELGRADE
 * @method static TZ_EUROPE_KALININGRAD
 * @method static TZ_EUROPE_MOSCOW
 * @method static TZ_EUROPE_SAMARA
 * @method static TZ_ASIA_YEKATERINBURG
 * @method static TZ_ASIA_OMSK
 * @method static TZ_ASIA_KRASNOYARSK
 * @method static TZ_ASIA_IRKUTSK
 * @method static TZ_ASIA_YAKUTSK
 * @method static TZ_ASIA_VLADIVOSTOK
 * @method static TZ_ASIA_MAGADAN
 * @method static TZ_ASIA_KAMCHATKA
 * @method static TZ_ASIA_RIYADH
 * @method static TZ_EUROPE_STOCKHOLM
 * @method static TZ_ASIA_SINGAPORE
 * @method static TZ_EUROPE_LJUBLJANA
 * @method static TZ_EUROPE_BRATISLAVA
 * @method static TZ_AMERICA_EL_SALVADOR
 * @method static TZ_ASIA_BANGKOK
 * @method static TZ_AFRICA_TUNIS
 * @method static TZ_EUROPE_ISTANBUL
 * @method static TZ_AMERICA_PORT_OF_SPAIN
 * @method static TZ_ASIA_TAIPEI
 * @method static TZ_EUROPE_KIEV
 * @method static TZ_AMERICA_MONTEVIDEO
 * @method static TZ_AMERICA_CARACAS
 * @method static TZ_ASIA_HO_CHI_MINH
 * @method static TZ_AFRICA_JOHANNESBURG
 * @method static TZ_AMERICA_WINNIPEG
 * @method static TZ_AMERICA_DETROIT
 * @method static TZ_AUSTRALIA_MELBOURNE
 * @method static TZ_ASIA_KATHMANDU
 * @method static TZ_ASIA_BAKU
 * @method static TZ_AFRICA_ABIDJAN
 * @method static TZ_AFRICA_ADDIS_ABABA
 * @method static TZ_AFRICA_ALGIERS
 * @method static TZ_AFRICA_ASMARA
 * @method static TZ_AFRICA_BAMAKO
 * @method static TZ_AFRICA_BANGUI
 * @method static TZ_AFRICA_BANJUL
 * @method static TZ_AFRICA_BISSAU
 * @method static TZ_AFRICA_BLANTYRE
 * @method static TZ_AFRICA_BRAZZAVILLE
 * @method static TZ_AFRICA_BUJUMBURA
 * @method static TZ_AFRICA_CEUTA
 * @method static TZ_AFRICA_CONAKRY
 * @method static TZ_AFRICA_DAKAR
 * @method static TZ_AFRICA_DAR_ES_SALAAM
 * @method static TZ_AFRICA_DJIBOUTI
 * @method static TZ_AFRICA_DOUALA
 * @method static TZ_AFRICA_EL_AAIUN
 * @method static TZ_AFRICA_FREETOWN
 * @method static TZ_AFRICA_GABORONE
 * @method static TZ_AFRICA_HARARE
 * @method static TZ_AFRICA_JUBA
 * @method static TZ_AFRICA_KAMPALA
 * @method static TZ_AFRICA_KHARTOUM
 * @method static TZ_AFRICA_KIGALI
 * @method static TZ_AFRICA_KINSHASA
 * @method static TZ_AFRICA_LIBREVILLE
 * @method static TZ_AFRICA_LOME
 * @method static TZ_AFRICA_LUANDA
 * @method static TZ_AFRICA_LUBUMBASHI
 * @method static TZ_AFRICA_LUSAKA
 * @method static TZ_AFRICA_MALABO
 * @method static TZ_AFRICA_MAPUTO
 * @method static TZ_AFRICA_MASERU
 * @method static TZ_AFRICA_MBABANE
 * @method static TZ_AFRICA_MOGADISHU
 * @method static TZ_AFRICA_MONROVIA
 * @method static TZ_AFRICA_NDJAMENA
 * @method static TZ_AFRICA_NIAMEY
 * @method static TZ_AFRICA_NOUAKCHOTT
 * @method static TZ_AFRICA_OUAGADOUGOU
 * @method static TZ_AFRICA_PORTO_NOVO
 * @method static TZ_AFRICA_SAO_TOME
 * @method static TZ_AFRICA_TRIPOLI
 * @method static TZ_AFRICA_WINDHOEK
 * @method static TZ_AMERICA_ADAK
 * @method static TZ_AMERICA_ANGUILLA
 * @method static TZ_AMERICA_ANTIGUA
 * @method static TZ_AMERICA_ARAGUAINA
 * @method static TZ_AMERICA_ARGENTINA_CATAMARCA
 * @method static TZ_AMERICA_ARGENTINA_CORDOBA
 * @method static TZ_AMERICA_ARGENTINA_JUJUY
 * @method static TZ_AMERICA_ARGENTINA_LA_RIOJA
 * @method static TZ_AMERICA_ARGENTINA_MENDOZA
 * @method static TZ_AMERICA_ARGENTINA_RIO_GALLEGOS
 * @method static TZ_AMERICA_ARGENTINA_SAN_JUAN
 * @method static TZ_AMERICA_ARGENTINA_TUCUMAN
 * @method static TZ_AMERICA_ARGENTINA_USHUAIA
 * @method static TZ_AMERICA_ARUBA
 * @method static TZ_AMERICA_BAHIA
 * @method static TZ_AMERICA_BAHIA_BANDERAS
 * @method static TZ_AMERICA_BARBADOS
 * @method static TZ_AMERICA_BELIZE
 * @method static TZ_AMERICA_BOA_VISTA
 * @method static TZ_AMERICA_BOISE
 * @method static TZ_AMERICA_CAMBRIDGE_BAY
 * @method static TZ_AMERICA_CANCUN
 * @method static TZ_AMERICA_CAYENNE
 * @method static TZ_AMERICA_CAYMAN
 * @method static TZ_AMERICA_CHIHUAHUA
 * @method static TZ_AMERICA_CRESTON
 * @method static TZ_AMERICA_CUIABA
 * @method static TZ_AMERICA_CURACAO
 * @method static TZ_AMERICA_DANMARKSHAVN
 * @method static TZ_AMERICA_DOMINICA
 * @method static TZ_AMERICA_EIRUNEPE
 * @method static TZ_AMERICA_FORT_NELSON
 * @method static TZ_AMERICA_FORTALEZA
 * @method static TZ_AMERICA_GLACE_BAY
 * @method static TZ_AMERICA_GODTHAB
 * @method static TZ_AMERICA_GOOSE_BAY
 * @method static TZ_AMERICA_GRAND_TURK
 * @method static TZ_AMERICA_GRENADA
 * @method static TZ_AMERICA_GUADELOUPE
 * @method static TZ_AMERICA_GUYANA
 * @method static TZ_AMERICA_HAVANA
 * @method static TZ_AMERICA_INDIANA_INDIANAPOLIS
 * @method static TZ_AMERICA_INDIANA_KNOX
 * @method static TZ_AMERICA_INDIANA_MARENGO
 * @method static TZ_AMERICA_INDIANA_PETERSBURG
 * @method static TZ_AMERICA_INDIANA_TELL_CITY
 * @method static TZ_AMERICA_INDIANA_VEVAY
 * @method static TZ_AMERICA_INDIANA_VINCENNES
 * @method static TZ_AMERICA_INDIANA_WINAMAC
 * @method static TZ_AMERICA_INDIANAPOLIS
 * @method static TZ_AMERICA_INUVIK
 * @method static TZ_AMERICA_JUNEAU
 * @method static TZ_AMERICA_KENTUCKY_LOUISVILLE
 * @method static TZ_AMERICA_KENTUCKY_MONTICELLO
 * @method static TZ_AMERICA_KRALENDIJK
 * @method static TZ_AMERICA_LOWER_PRINCES
 * @method static TZ_AMERICA_MACEIO
 * @method static TZ_AMERICA_MANAUS
 * @method static TZ_AMERICA_MARIGOT
 * @method static TZ_AMERICA_MARTINIQUE
 * @method static TZ_AMERICA_MATAMOROS
 * @method static TZ_AMERICA_MENOMINEE
 * @method static TZ_AMERICA_MERIDA
 * @method static TZ_AMERICA_METLAKATLA
 * @method static TZ_AMERICA_MIQUELON
 * @method static TZ_AMERICA_MONCTON
 * @method static TZ_AMERICA_MONTERREY
 * @method static TZ_AMERICA_MONTREAL
 * @method static TZ_AMERICA_MONTSERRAT
 * @method static TZ_AMERICA_NIPIGON
 * @method static TZ_AMERICA_NOME
 * @method static TZ_AMERICA_NORTH_DAKOTA_BEULAH
 * @method static TZ_AMERICA_NORTH_DAKOTA_CENTER
 * @method static TZ_AMERICA_NORTH_DAKOTA_NEW_SALEM
 * @method static TZ_AMERICA_OJINAGA
 * @method static TZ_AMERICA_PANGNIRTUNG
 * @method static TZ_AMERICA_PARAMARIBO
 * @method static TZ_AMERICA_PORT_AU_PRINCE
 * @method static TZ_AMERICA_PORTO_VELHO
 * @method static TZ_AMERICA_PUNTA_ARENAS
 * @method static TZ_AMERICA_RANKIN_INLET
 * @method static TZ_AMERICA_RECIFE
 * @method static TZ_AMERICA_RESOLUTE
 * @method static TZ_AMERICA_RIO_BRANCO
 * @method static TZ_AMERICA_SANTAREM
 * @method static TZ_AMERICA_SCORESBYSUND
 * @method static TZ_AMERICA_SITKA
 * @method static TZ_AMERICA_ST_BARTHELEMY
 * @method static TZ_AMERICA_ST_KITTS
 * @method static TZ_AMERICA_ST_LUCIA
 * @method static TZ_AMERICA_ST_THOMAS
 * @method static TZ_AMERICA_ST_VINCENT
 * @method static TZ_AMERICA_SWIFT_CURRENT
 * @method static TZ_AMERICA_THULE
 * @method static TZ_AMERICA_THUNDER_BAY
 * @method static TZ_AMERICA_TORTOLA
 * @method static TZ_AMERICA_WHITEHORSE
 * @method static TZ_AMERICA_YAKUTAT
 * @method static TZ_AMERICA_YELLOWKNIFE
 * @method static TZ_ANTARCTICA_CASEY
 * @method static TZ_ANTARCTICA_DAVIS
 * @method static TZ_ANTARCTICA_DUMONTDURVILLE
 * @method static TZ_ANTARCTICA_MACQUARIE
 * @method static TZ_ANTARCTICA_MAWSON
 * @method static TZ_ANTARCTICA_MCMURDO
 * @method static TZ_ANTARCTICA_PALMER
 * @method static TZ_ANTARCTICA_ROTHERA
 * @method static TZ_ANTARCTICA_SYOWA
 * @method static TZ_ANTARCTICA_TROLL
 * @method static TZ_ANTARCTICA_VOSTOK
 * @method static TZ_ARCTIC_LONGYEARBYEN
 * @method static TZ_ASIA_ADEN
 * @method static TZ_ASIA_ALMATY
 * @method static TZ_ASIA_ANADYR
 * @method static TZ_ASIA_AQTAU
 * @method static TZ_ASIA_AQTOBE
 * @method static TZ_ASIA_ASHGABAT
 * @method static TZ_ASIA_ATYRAU
 * @method static TZ_ASIA_BARNAUL
 * @method static TZ_ASIA_BISHKEK
 * @method static TZ_ASIA_BRUNEI
 * @method static TZ_ASIA_CHITA
 * @method static TZ_ASIA_CHOIBALSAN
 * @method static TZ_ASIA_DAMASCUS
 * @method static TZ_ASIA_DILI
 * @method static TZ_ASIA_DUSHANBE
 * @method static TZ_ASIA_FAMAGUSTA
 * @method static TZ_ASIA_HEBRON
 * @method static TZ_ASIA_HOVD
 * @method static TZ_ASIA_ISTANBUL
 * @method static TZ_ASIA_KABUL
 * @method static TZ_ASIA_KHANDYGA
 * @method static TZ_ASIA_KUCHING
 * @method static TZ_ASIA_MACAU
 * @method static TZ_ASIA_NOVOKUZNETSK
 * @method static TZ_ASIA_NOVOSIBIRSK
 * @method static TZ_ASIA_ORAL
 * @method static TZ_ASIA_PHNOM_PENH
 * @method static TZ_ASIA_PONTIANAK
 * @method static TZ_ASIA_PYONGYANG
 * @method static TZ_ASIA_QOSTANAY
 * @method static TZ_ASIA_QYZYLORDA
 * @method static TZ_ASIA_SAKHALIN
 * @method static TZ_ASIA_SAMARKAND
 * @method static TZ_ASIA_SREDNEKOLYMSK
 * @method static TZ_ASIA_TASHKENT
 * @method static TZ_ASIA_TBILISI
 * @method static TZ_ASIA_TEHRAN
 * @method static TZ_ASIA_THIMPHU
 * @method static TZ_ASIA_TOMSK
 * @method static TZ_ASIA_ULAANBAATAR
 * @method static TZ_ASIA_URUMQI
 * @method static TZ_ASIA_UST_NERA
 * @method static TZ_ASIA_VIENTIANE
 * @method static TZ_ASIA_YANGON
 * @method static TZ_ASIA_YEREVAN
 * @method static TZ_ATLANTIC_BERMUDA
 * @method static TZ_ATLANTIC_CAPE_VERDE
 * @method static TZ_ATLANTIC_FAROE
 * @method static TZ_ATLANTIC_MADEIRA
 * @method static TZ_ATLANTIC_SOUTH_GEORGIA
 * @method static TZ_ATLANTIC_ST_HELENA
 * @method static TZ_ATLANTIC_STANLEY
 * @method static TZ_AUSTRALIA_ADELAIDE
 * @method static TZ_AUSTRALIA_BRISBANE
 * @method static TZ_AUSTRALIA_CURRIE
 * @method static TZ_AUSTRALIA_DARWIN
 * @method static TZ_AUSTRALIA_EUCLA
 * @method static TZ_AUSTRALIA_HOBART
 * @method static TZ_AUSTRALIA_LINDEMAN
 * @method static TZ_AUSTRALIA_LORD_HOWE
 * @method static TZ_CET
 * @method static TZ_CST6CDT
 * @method static TZ_EET
 * @method static TZ_EST
 * @method static TZ_EST5EDT
 * @method static TZ_ETC_GMT
 * @method static TZ_ETC_GMT_PLUS_0
 * @method static TZ_ETC_GMT_PLUS_1
 * @method static TZ_ETC_GMT_PLUS_10
 * @method static TZ_ETC_GMT_PLUS_11
 * @method static TZ_ETC_GMT_PLUS_12
 * @method static TZ_ETC_GMT_PLUS_2
 * @method static TZ_ETC_GMT_PLUS_3
 * @method static TZ_ETC_GMT_PLUS_4
 * @method static TZ_ETC_GMT_PLUS_5
 * @method static TZ_ETC_GMT_PLUS_6
 * @method static TZ_ETC_GMT_PLUS_7
 * @method static TZ_ETC_GMT_PLUS_8
 * @method static TZ_ETC_GMT_PLUS_9
 * @method static TZ_ETC_GMT_MINUS_0
 * @method static TZ_ETC_GMT_MINUS_1
 * @method static TZ_ETC_GMT_MINUS_10
 * @method static TZ_ETC_GMT_MINUS_11
 * @method static TZ_ETC_GMT_MINUS_12
 * @method static TZ_ETC_GMT_MINUS_13
 * @method static TZ_ETC_GMT_MINUS_14
 * @method static TZ_ETC_GMT_MINUS_2
 * @method static TZ_ETC_GMT_MINUS_3
 * @method static TZ_ETC_GMT_MINUS_4
 * @method static TZ_ETC_GMT_MINUS_5
 * @method static TZ_ETC_GMT_MINUS_6
 * @method static TZ_ETC_GMT_MINUS_7
 * @method static TZ_ETC_GMT_MINUS_8
 * @method static TZ_ETC_GMT_MINUS_9
 * @method static TZ_ETC_GMT0
 * @method static TZ_ETC_GREENWICH
 * @method static TZ_ETC_UNIVERSAL
 * @method static TZ_ETC_ZULU
 * @method static TZ_EUROPE_ANDORRA
 * @method static TZ_EUROPE_ASTRAKHAN
 * @method static TZ_EUROPE_BUSINGEN
 * @method static TZ_EUROPE_CHISINAU
 * @method static TZ_EUROPE_GIBRALTAR
 * @method static TZ_EUROPE_GUERNSEY
 * @method static TZ_EUROPE_ISLE_OF_MAN
 * @method static TZ_EUROPE_JERSEY
 * @method static TZ_EUROPE_KIROV
 * @method static TZ_EUROPE_MARIEHAMN
 * @method static TZ_EUROPE_MINSK
 * @method static TZ_EUROPE_MONACO
 * @method static TZ_EUROPE_NICOSIA
 * @method static TZ_EUROPE_PODGORICA
 * @method static TZ_EUROPE_SAN_MARINO
 * @method static TZ_EUROPE_SARATOV
 * @method static TZ_EUROPE_SIMFEROPOL
 * @method static TZ_EUROPE_TIRANE
 * @method static TZ_EUROPE_ULYANOVSK
 * @method static TZ_EUROPE_UZHGOROD
 * @method static TZ_EUROPE_VADUZ
 * @method static TZ_EUROPE_VATICAN
 * @method static TZ_EUROPE_VOLGOGRAD
 * @method static TZ_EUROPE_ZAPOROZHYE
 * @method static TZ_GMT
 * @method static TZ_HST
 * @method static TZ_INDIAN_ANTANANARIVO
 * @method static TZ_INDIAN_CHAGOS
 * @method static TZ_INDIAN_CHRISTMAS
 * @method static TZ_INDIAN_COCOS
 * @method static TZ_INDIAN_COMORO
 * @method static TZ_INDIAN_KERGUELEN
 * @method static TZ_INDIAN_MAHE
 * @method static TZ_INDIAN_MAYOTTE
 * @method static TZ_INDIAN_REUNION
 * @method static TZ_MET
 * @method static TZ_MST
 * @method static TZ_MST7MDT
 * @method static TZ_PST8PDT
 * @method static TZ_PACIFIC_APIA
 * @method static TZ_PACIFIC_BOUGAINVILLE
 * @method static TZ_PACIFIC_CHATHAM
 * @method static TZ_PACIFIC_CHUUK
 * @method static TZ_PACIFIC_EFATE
 * @method static TZ_PACIFIC_ENDERBURY
 * @method static TZ_PACIFIC_FAKAOFO
 * @method static TZ_PACIFIC_FIJI
 * @method static TZ_PACIFIC_FUNAFUTI
 * @method static TZ_PACIFIC_GAMBIER
 * @method static TZ_PACIFIC_GUADALCANAL
 * @method static TZ_PACIFIC_GUAM
 * @method static TZ_PACIFIC_KIRITIMATI
 * @method static TZ_PACIFIC_KOSRAE
 * @method static TZ_PACIFIC_KWAJALEIN
 * @method static TZ_PACIFIC_MAJURO
 * @method static TZ_PACIFIC_MARQUESAS
 * @method static TZ_PACIFIC_MIDWAY
 * @method static TZ_PACIFIC_NAURU
 * @method static TZ_PACIFIC_NIUE
 * @method static TZ_PACIFIC_NORFOLK
 * @method static TZ_PACIFIC_NOUMEA
 * @method static TZ_PACIFIC_PAGO_PAGO
 * @method static TZ_PACIFIC_PALAU
 * @method static TZ_PACIFIC_PITCAIRN
 * @method static TZ_PACIFIC_POHNPEI
 * @method static TZ_PACIFIC_PORT_MORESBY
 * @method static TZ_PACIFIC_RAROTONGA
 * @method static TZ_PACIFIC_SAIPAN
 * @method static TZ_PACIFIC_TAHITI
 * @method static TZ_PACIFIC_TARAWA
 * @method static TZ_PACIFIC_TONGATAPU
 * @method static TZ_PACIFIC_WAKE
 * @method static TZ_PACIFIC_WALLIS
 * @method static TZ_UTC
 * @method static TZ_WET
 * @method static TZ_ASIA_CALCUTTA
 * @method static TZ_ASIA_KATMANDU
 * @method static TZ_AMERICA_NUUK
 * @method static TZ_NUM_TIMEZONES
 */
class FacebookTimezoneEnum extends Enumerate
{
    const TZ_UNKNOWN = 0;
    const TZ_AMERICA_LOS_ANGELES = 1;
    const TZ_AMERICA_DENVER = 2;
    const TZ_PACIFIC_HONOLULU = 3;
    const TZ_AMERICA_ANCHORAGE = 4;
    const TZ_AMERICA_PHOENIX = 5;
    const TZ_AMERICA_CHICAGO = 6;
    const TZ_AMERICA_NEW_YORK = 7;
    const TZ_ASIA_DUBAI = 8;
    const TZ_AMERICA_ARGENTINA_SAN_LUIS = 9;
    const TZ_AMERICA_ARGENTINA_BUENOS_AIRES = 10;
    const TZ_AMERICA_ARGENTINA_SALTA = 11;
    const TZ_EUROPE_VIENNA = 12;
    const TZ_AUSTRALIA_PERTH = 13;
    const TZ_AUSTRALIA_BROKEN_HILL = 14;
    const TZ_AUSTRALIA_SYDNEY = 15;
    const TZ_EUROPE_SARAJEVO = 16;
    const TZ_ASIA_DHAKA = 17;
    const TZ_EUROPE_BRUSSELS = 18;
    const TZ_EUROPE_SOFIA = 19;
    const TZ_ASIA_BAHRAIN = 20;
    const TZ_AMERICA_LA_PAZ = 21;
    const TZ_AMERICA_NORONHA = 22;
    const TZ_AMERICA_CAMPO_GRANDE = 23;
    const TZ_AMERICA_BELEM = 24;
    const TZ_AMERICA_SAO_PAULO = 25;
    const TZ_AMERICA_NASSAU = 26;
    const TZ_AMERICA_DAWSON = 27;
    const TZ_AMERICA_VANCOUVER = 28;
    const TZ_AMERICA_DAWSON_CREEK = 29;
    const TZ_AMERICA_EDMONTON = 30;
    const TZ_AMERICA_RAINY_RIVER = 31;
    const TZ_AMERICA_REGINA = 32;
    const TZ_AMERICA_ATIKOKAN = 33;
    const TZ_AMERICA_IQALUIT = 34;
    const TZ_AMERICA_TORONTO = 35;
    const TZ_AMERICA_BLANC_SABLON = 36;
    const TZ_AMERICA_HALIFAX = 37;
    const TZ_AMERICA_ST_JOHNS = 38;
    const TZ_EUROPE_ZURICH = 39;
    const TZ_PACIFIC_EASTER = 40;
    const TZ_AMERICA_SANTIAGO = 41;
    const TZ_ASIA_SHANGHAI = 42;
    const TZ_AMERICA_BOGOTA = 43;
    const TZ_AMERICA_COSTA_RICA = 44;
    const TZ_ASIA_NICOSIA = 45;
    const TZ_EUROPE_PRAGUE = 46;
    const TZ_EUROPE_BERLIN = 47;
    const TZ_EUROPE_COPENHAGEN = 48;
    const TZ_AMERICA_SANTO_DOMINGO = 49;
    const TZ_PACIFIC_GALAPAGOS = 50;
    const TZ_AMERICA_GUAYAQUIL = 51;
    const TZ_EUROPE_TALLINN = 52;
    const TZ_AFRICA_CAIRO = 53;
    const TZ_ATLANTIC_CANARY = 54;
    const TZ_EUROPE_MADRID = 55;
    const TZ_EUROPE_HELSINKI = 56;
    const TZ_EUROPE_PARIS = 57;
    const TZ_EUROPE_LONDON = 58;
    const TZ_AFRICA_ACCRA = 59;
    const TZ_EUROPE_ATHENS = 60;
    const TZ_AMERICA_GUATEMALA = 61;
    const TZ_ASIA_HONG_KONG = 62;
    const TZ_AMERICA_TEGUCIGALPA = 63;
    const TZ_EUROPE_ZAGREB = 64;
    const TZ_EUROPE_BUDAPEST = 65;
    const TZ_ASIA_JAKARTA = 66;
    const TZ_ASIA_MAKASSAR = 67;
    const TZ_ASIA_JAYAPURA = 68;
    const TZ_EUROPE_DUBLIN = 69;
    const TZ_ASIA_JERUSALEM = 70;
    const TZ_ASIA_KOLKATA = 71;
    const TZ_ASIA_BAGHDAD = 72;
    const TZ_ATLANTIC_REYKJAVIK = 73;
    const TZ_EUROPE_ROME = 74;
    const TZ_AMERICA_JAMAICA = 75;
    const TZ_ASIA_AMMAN = 76;
    const TZ_ASIA_TOKYO = 77;
    const TZ_AFRICA_NAIROBI = 78;
    const TZ_ASIA_SEOUL = 79;
    const TZ_ASIA_KUWAIT = 80;
    const TZ_ASIA_BEIRUT = 81;
    const TZ_ASIA_COLOMBO = 82;
    const TZ_EUROPE_VILNIUS = 83;
    const TZ_EUROPE_LUXEMBOURG = 84;
    const TZ_EUROPE_RIGA = 85;
    const TZ_AFRICA_CASABLANCA = 86;
    const TZ_EUROPE_SKOPJE = 87;
    const TZ_EUROPE_MALTA = 88;
    const TZ_INDIAN_MAURITIUS = 89;
    const TZ_INDIAN_MALDIVES = 90;
    const TZ_AMERICA_TIJUANA = 91;
    const TZ_AMERICA_HERMOSILLO = 92;
    const TZ_AMERICA_MAZATLAN = 93;
    const TZ_AMERICA_MEXICO_CITY = 94;
    const TZ_ASIA_KUALA_LUMPUR = 95;
    const TZ_AFRICA_LAGOS = 96;
    const TZ_AMERICA_MANAGUA = 97;
    const TZ_EUROPE_AMSTERDAM = 98;
    const TZ_EUROPE_OSLO = 99;
    const TZ_PACIFIC_AUCKLAND = 100;
    const TZ_ASIA_MUSCAT = 101;
    const TZ_AMERICA_PANAMA = 102;
    const TZ_AMERICA_LIMA = 103;
    const TZ_ASIA_MANILA = 104;
    const TZ_ASIA_KARACHI = 105;
    const TZ_EUROPE_WARSAW = 106;
    const TZ_AMERICA_PUERTO_RICO = 107;
    const TZ_ASIA_GAZA = 108;
    const TZ_ATLANTIC_AZORES = 109;
    const TZ_EUROPE_LISBON = 110;
    const TZ_AMERICA_ASUNCION = 111;
    const TZ_ASIA_QATAR = 112;
    const TZ_EUROPE_BUCHAREST = 113;
    const TZ_EUROPE_BELGRADE = 114;
    const TZ_EUROPE_KALININGRAD = 115;
    const TZ_EUROPE_MOSCOW = 116;
    const TZ_EUROPE_SAMARA = 117;
    const TZ_ASIA_YEKATERINBURG = 118;
    const TZ_ASIA_OMSK = 119;
    const TZ_ASIA_KRASNOYARSK = 120;
    const TZ_ASIA_IRKUTSK = 121;
    const TZ_ASIA_YAKUTSK = 122;
    const TZ_ASIA_VLADIVOSTOK = 123;
    const TZ_ASIA_MAGADAN = 124;
    const TZ_ASIA_KAMCHATKA = 125;
    const TZ_ASIA_RIYADH = 126;
    const TZ_EUROPE_STOCKHOLM = 127;
    const TZ_ASIA_SINGAPORE = 128;
    const TZ_EUROPE_LJUBLJANA = 129;
    const TZ_EUROPE_BRATISLAVA = 130;
    const TZ_AMERICA_EL_SALVADOR = 131;
    const TZ_ASIA_BANGKOK = 132;
    const TZ_AFRICA_TUNIS = 133;
    const TZ_EUROPE_ISTANBUL = 134;
    const TZ_AMERICA_PORT_OF_SPAIN = 135;
    const TZ_ASIA_TAIPEI = 136;
    const TZ_EUROPE_KIEV = 137;
    const TZ_AMERICA_MONTEVIDEO = 138;
    const TZ_AMERICA_CARACAS = 139;
    const TZ_ASIA_HO_CHI_MINH = 140;
    const TZ_AFRICA_JOHANNESBURG = 141;
    const TZ_AMERICA_WINNIPEG = 142;
    const TZ_AMERICA_DETROIT = 143;
    const TZ_AUSTRALIA_MELBOURNE = 144;
    const TZ_ASIA_KATHMANDU = 145;
    const TZ_ASIA_BAKU = 146;
    const TZ_AFRICA_ABIDJAN = 147;
    const TZ_AFRICA_ADDIS_ABABA = 148;
    const TZ_AFRICA_ALGIERS = 149;
    const TZ_AFRICA_ASMARA = 150;
    const TZ_AFRICA_BAMAKO = 151;
    const TZ_AFRICA_BANGUI = 152;
    const TZ_AFRICA_BANJUL = 153;
    const TZ_AFRICA_BISSAU = 154;
    const TZ_AFRICA_BLANTYRE = 155;
    const TZ_AFRICA_BRAZZAVILLE = 156;
    const TZ_AFRICA_BUJUMBURA = 157;
    const TZ_AFRICA_CEUTA = 158;
    const TZ_AFRICA_CONAKRY = 159;
    const TZ_AFRICA_DAKAR = 160;
    const TZ_AFRICA_DAR_ES_SALAAM = 161;
    const TZ_AFRICA_DJIBOUTI = 162;
    const TZ_AFRICA_DOUALA = 163;
    const TZ_AFRICA_EL_AAIUN = 164;
    const TZ_AFRICA_FREETOWN = 165;
    const TZ_AFRICA_GABORONE = 166;
    const TZ_AFRICA_HARARE = 167;
    const TZ_AFRICA_JUBA = 168;
    const TZ_AFRICA_KAMPALA = 169;
    const TZ_AFRICA_KHARTOUM = 170;
    const TZ_AFRICA_KIGALI = 171;
    const TZ_AFRICA_KINSHASA = 172;
    const TZ_AFRICA_LIBREVILLE = 173;
    const TZ_AFRICA_LOME = 174;
    const TZ_AFRICA_LUANDA = 175;
    const TZ_AFRICA_LUBUMBASHI = 176;
    const TZ_AFRICA_LUSAKA = 177;
    const TZ_AFRICA_MALABO = 178;
    const TZ_AFRICA_MAPUTO = 179;
    const TZ_AFRICA_MASERU = 180;
    const TZ_AFRICA_MBABANE = 181;
    const TZ_AFRICA_MOGADISHU = 182;
    const TZ_AFRICA_MONROVIA = 183;
    const TZ_AFRICA_NDJAMENA = 184;
    const TZ_AFRICA_NIAMEY = 185;
    const TZ_AFRICA_NOUAKCHOTT = 186;
    const TZ_AFRICA_OUAGADOUGOU = 187;
    const TZ_AFRICA_PORTO_NOVO = 188;
    const TZ_AFRICA_SAO_TOME = 189;
    const TZ_AFRICA_TRIPOLI = 190;
    const TZ_AFRICA_WINDHOEK = 191;
    const TZ_AMERICA_ADAK = 192;
    const TZ_AMERICA_ANGUILLA = 193;
    const TZ_AMERICA_ANTIGUA = 194;
    const TZ_AMERICA_ARAGUAINA = 195;
    const TZ_AMERICA_ARGENTINA_CATAMARCA = 196;
    const TZ_AMERICA_ARGENTINA_CORDOBA = 197;
    const TZ_AMERICA_ARGENTINA_JUJUY = 198;
    const TZ_AMERICA_ARGENTINA_LA_RIOJA = 199;
    const TZ_AMERICA_ARGENTINA_MENDOZA = 200;
    const TZ_AMERICA_ARGENTINA_RIO_GALLEGOS = 201;
    const TZ_AMERICA_ARGENTINA_SAN_JUAN = 202;
    const TZ_AMERICA_ARGENTINA_TUCUMAN = 203;
    const TZ_AMERICA_ARGENTINA_USHUAIA = 204;
    const TZ_AMERICA_ARUBA = 205;
    const TZ_AMERICA_BAHIA = 206;
    const TZ_AMERICA_BAHIA_BANDERAS = 207;
    const TZ_AMERICA_BARBADOS = 208;
    const TZ_AMERICA_BELIZE = 209;
    const TZ_AMERICA_BOA_VISTA = 210;
    const TZ_AMERICA_BOISE = 211;
    const TZ_AMERICA_CAMBRIDGE_BAY = 212;
    const TZ_AMERICA_CANCUN = 213;
    const TZ_AMERICA_CAYENNE = 214;
    const TZ_AMERICA_CAYMAN = 215;
    const TZ_AMERICA_CHIHUAHUA = 216;
    const TZ_AMERICA_CRESTON = 217;
    const TZ_AMERICA_CUIABA = 218;
    const TZ_AMERICA_CURACAO = 219;
    const TZ_AMERICA_DANMARKSHAVN = 220;
    const TZ_AMERICA_DOMINICA = 221;
    const TZ_AMERICA_EIRUNEPE = 222;
    const TZ_AMERICA_FORT_NELSON = 223;
    const TZ_AMERICA_FORTALEZA = 224;
    const TZ_AMERICA_GLACE_BAY = 225;
    const TZ_AMERICA_GODTHAB = 226;
    const TZ_AMERICA_GOOSE_BAY = 227;
    const TZ_AMERICA_GRAND_TURK = 228;
    const TZ_AMERICA_GRENADA = 229;
    const TZ_AMERICA_GUADELOUPE = 230;
    const TZ_AMERICA_GUYANA = 231;
    const TZ_AMERICA_HAVANA = 232;
    const TZ_AMERICA_INDIANA_INDIANAPOLIS = 233;
    const TZ_AMERICA_INDIANA_KNOX = 234;
    const TZ_AMERICA_INDIANA_MARENGO = 235;
    const TZ_AMERICA_INDIANA_PETERSBURG = 236;
    const TZ_AMERICA_INDIANA_TELL_CITY = 237;
    const TZ_AMERICA_INDIANA_VEVAY = 238;
    const TZ_AMERICA_INDIANA_VINCENNES = 239;
    const TZ_AMERICA_INDIANA_WINAMAC = 240;
    const TZ_AMERICA_INDIANAPOLIS = 241;
    const TZ_AMERICA_INUVIK = 242;
    const TZ_AMERICA_JUNEAU = 243;
    const TZ_AMERICA_KENTUCKY_LOUISVILLE = 244;
    const TZ_AMERICA_KENTUCKY_MONTICELLO = 245;
    const TZ_AMERICA_KRALENDIJK = 246;
    const TZ_AMERICA_LOWER_PRINCES = 247;
    const TZ_AMERICA_MACEIO = 248;
    const TZ_AMERICA_MANAUS = 249;
    const TZ_AMERICA_MARIGOT = 250;
    const TZ_AMERICA_MARTINIQUE = 251;
    const TZ_AMERICA_MATAMOROS = 252;
    const TZ_AMERICA_MENOMINEE = 253;
    const TZ_AMERICA_MERIDA = 254;
    const TZ_AMERICA_METLAKATLA = 255;
    const TZ_AMERICA_MIQUELON = 256;
    const TZ_AMERICA_MONCTON = 257;
    const TZ_AMERICA_MONTERREY = 258;
    const TZ_AMERICA_MONTREAL = 259;
    const TZ_AMERICA_MONTSERRAT = 260;
    const TZ_AMERICA_NIPIGON = 261;
    const TZ_AMERICA_NOME = 262;
    const TZ_AMERICA_NORTH_DAKOTA_BEULAH = 263;
    const TZ_AMERICA_NORTH_DAKOTA_CENTER = 264;
    const TZ_AMERICA_NORTH_DAKOTA_NEW_SALEM = 265;
    const TZ_AMERICA_OJINAGA = 266;
    const TZ_AMERICA_PANGNIRTUNG = 267;
    const TZ_AMERICA_PARAMARIBO = 268;
    const TZ_AMERICA_PORT_AU_PRINCE = 269;
    const TZ_AMERICA_PORTO_VELHO = 270;
    const TZ_AMERICA_PUNTA_ARENAS = 271;
    const TZ_AMERICA_RANKIN_INLET = 272;
    const TZ_AMERICA_RECIFE = 273;
    const TZ_AMERICA_RESOLUTE = 274;
    const TZ_AMERICA_RIO_BRANCO = 275;
    const TZ_AMERICA_SANTAREM = 276;
    const TZ_AMERICA_SCORESBYSUND = 277;
    const TZ_AMERICA_SITKA = 278;
    const TZ_AMERICA_ST_BARTHELEMY = 279;
    const TZ_AMERICA_ST_KITTS = 280;
    const TZ_AMERICA_ST_LUCIA = 281;
    const TZ_AMERICA_ST_THOMAS = 282;
    const TZ_AMERICA_ST_VINCENT = 283;
    const TZ_AMERICA_SWIFT_CURRENT = 284;
    const TZ_AMERICA_THULE = 285;
    const TZ_AMERICA_THUNDER_BAY = 286;
    const TZ_AMERICA_TORTOLA = 287;
    const TZ_AMERICA_WHITEHORSE = 288;
    const TZ_AMERICA_YAKUTAT = 289;
    const TZ_AMERICA_YELLOWKNIFE = 290;
    const TZ_ANTARCTICA_CASEY = 291;
    const TZ_ANTARCTICA_DAVIS = 292;
    const TZ_ANTARCTICA_DUMONTDURVILLE = 293;
    const TZ_ANTARCTICA_MACQUARIE = 294;
    const TZ_ANTARCTICA_MAWSON = 295;
    const TZ_ANTARCTICA_MCMURDO = 296;
    const TZ_ANTARCTICA_PALMER = 297;
    const TZ_ANTARCTICA_ROTHERA = 298;
    const TZ_ANTARCTICA_SYOWA = 299;
    const TZ_ANTARCTICA_TROLL = 300;
    const TZ_ANTARCTICA_VOSTOK = 301;
    const TZ_ARCTIC_LONGYEARBYEN = 302;
    const TZ_ASIA_ADEN = 303;
    const TZ_ASIA_ALMATY = 304;
    const TZ_ASIA_ANADYR = 305;
    const TZ_ASIA_AQTAU = 306;
    const TZ_ASIA_AQTOBE = 307;
    const TZ_ASIA_ASHGABAT = 308;
    const TZ_ASIA_ATYRAU = 309;
    const TZ_ASIA_BARNAUL = 310;
    const TZ_ASIA_BISHKEK = 311;
    const TZ_ASIA_BRUNEI = 312;
    const TZ_ASIA_CHITA = 313;
    const TZ_ASIA_CHOIBALSAN = 314;
    const TZ_ASIA_DAMASCUS = 315;
    const TZ_ASIA_DILI = 316;
    const TZ_ASIA_DUSHANBE = 317;
    const TZ_ASIA_FAMAGUSTA = 318;
    const TZ_ASIA_HEBRON = 319;
    const TZ_ASIA_HOVD = 320;
    const TZ_ASIA_ISTANBUL = 321;
    const TZ_ASIA_KABUL = 322;
    const TZ_ASIA_KHANDYGA = 323;
    const TZ_ASIA_KUCHING = 324;
    const TZ_ASIA_MACAU = 325;
    const TZ_ASIA_NOVOKUZNETSK = 326;
    const TZ_ASIA_NOVOSIBIRSK = 327;
    const TZ_ASIA_ORAL = 328;
    const TZ_ASIA_PHNOM_PENH = 329;
    const TZ_ASIA_PONTIANAK = 330;
    const TZ_ASIA_PYONGYANG = 331;
    const TZ_ASIA_QOSTANAY = 332;
    const TZ_ASIA_QYZYLORDA = 333;
    const TZ_ASIA_SAKHALIN = 334;
    const TZ_ASIA_SAMARKAND = 335;
    const TZ_ASIA_SREDNEKOLYMSK = 336;
    const TZ_ASIA_TASHKENT = 337;
    const TZ_ASIA_TBILISI = 338;
    const TZ_ASIA_TEHRAN = 339;
    const TZ_ASIA_THIMPHU = 340;
    const TZ_ASIA_TOMSK = 341;
    const TZ_ASIA_ULAANBAATAR = 342;
    const TZ_ASIA_URUMQI = 343;
    const TZ_ASIA_UST_NERA = 344;
    const TZ_ASIA_VIENTIANE = 345;
    const TZ_ASIA_YANGON = 346;
    const TZ_ASIA_YEREVAN = 347;
    const TZ_ATLANTIC_BERMUDA = 348;
    const TZ_ATLANTIC_CAPE_VERDE = 349;
    const TZ_ATLANTIC_FAROE = 350;
    const TZ_ATLANTIC_MADEIRA = 351;
    const TZ_ATLANTIC_SOUTH_GEORGIA = 352;
    const TZ_ATLANTIC_ST_HELENA = 353;
    const TZ_ATLANTIC_STANLEY = 354;
    const TZ_AUSTRALIA_ADELAIDE = 355;
    const TZ_AUSTRALIA_BRISBANE = 356;
    const TZ_AUSTRALIA_CURRIE = 357;
    const TZ_AUSTRALIA_DARWIN = 358;
    const TZ_AUSTRALIA_EUCLA = 359;
    const TZ_AUSTRALIA_HOBART = 360;
    const TZ_AUSTRALIA_LINDEMAN = 361;
    const TZ_AUSTRALIA_LORD_HOWE = 362;
    const TZ_CET = 363;
    const TZ_CST6CDT = 364;
    const TZ_EET = 365;
    const TZ_EST = 366;
    const TZ_EST5EDT = 367;
    const TZ_ETC_GMT = 368;
    const TZ_ETC_GMT_PLUS_0 = 369;
    const TZ_ETC_GMT_PLUS_1 = 370;
    const TZ_ETC_GMT_PLUS_10 = 371;
    const TZ_ETC_GMT_PLUS_11 = 372;
    const TZ_ETC_GMT_PLUS_12 = 373;
    const TZ_ETC_GMT_PLUS_2 = 374;
    const TZ_ETC_GMT_PLUS_3 = 375;
    const TZ_ETC_GMT_PLUS_4 = 376;
    const TZ_ETC_GMT_PLUS_5 = 377;
    const TZ_ETC_GMT_PLUS_6 = 378;
    const TZ_ETC_GMT_PLUS_7 = 379;
    const TZ_ETC_GMT_PLUS_8 = 380;
    const TZ_ETC_GMT_PLUS_9 = 381;
    const TZ_ETC_GMT_MINUS_0 = 382;
    const TZ_ETC_GMT_MINUS_1 = 383;
    const TZ_ETC_GMT_MINUS_10 = 384;
    const TZ_ETC_GMT_MINUS_11 = 385;
    const TZ_ETC_GMT_MINUS_12 = 386;
    const TZ_ETC_GMT_MINUS_13 = 387;
    const TZ_ETC_GMT_MINUS_14 = 388;
    const TZ_ETC_GMT_MINUS_2 = 389;
    const TZ_ETC_GMT_MINUS_3 = 390;
    const TZ_ETC_GMT_MINUS_4 = 391;
    const TZ_ETC_GMT_MINUS_5 = 392;
    const TZ_ETC_GMT_MINUS_6 = 393;
    const TZ_ETC_GMT_MINUS_7 = 394;
    const TZ_ETC_GMT_MINUS_8 = 395;
    const TZ_ETC_GMT_MINUS_9 = 396;
    const TZ_ETC_GMT0 = 397;
    const TZ_ETC_GREENWICH = 398;
    const TZ_ETC_UNIVERSAL = 399;
    const TZ_ETC_ZULU = 400;
    const TZ_EUROPE_ANDORRA = 401;
    const TZ_EUROPE_ASTRAKHAN = 402;
    const TZ_EUROPE_BUSINGEN = 403;
    const TZ_EUROPE_CHISINAU = 404;
    const TZ_EUROPE_GIBRALTAR = 405;
    const TZ_EUROPE_GUERNSEY = 406;
    const TZ_EUROPE_ISLE_OF_MAN = 407;
    const TZ_EUROPE_JERSEY = 408;
    const TZ_EUROPE_KIROV = 409;
    const TZ_EUROPE_MARIEHAMN = 410;
    const TZ_EUROPE_MINSK = 411;
    const TZ_EUROPE_MONACO = 412;
    const TZ_EUROPE_NICOSIA = 413;
    const TZ_EUROPE_PODGORICA = 414;
    const TZ_EUROPE_SAN_MARINO = 415;
    const TZ_EUROPE_SARATOV = 416;
    const TZ_EUROPE_SIMFEROPOL = 417;
    const TZ_EUROPE_TIRANE = 418;
    const TZ_EUROPE_ULYANOVSK = 419;
    const TZ_EUROPE_UZHGOROD = 420;
    const TZ_EUROPE_VADUZ = 421;
    const TZ_EUROPE_VATICAN = 422;
    const TZ_EUROPE_VOLGOGRAD = 423;
    const TZ_EUROPE_ZAPOROZHYE = 424;
    const TZ_GMT = 425;
    const TZ_HST = 426;
    const TZ_INDIAN_ANTANANARIVO = 427;
    const TZ_INDIAN_CHAGOS = 428;
    const TZ_INDIAN_CHRISTMAS = 429;
    const TZ_INDIAN_COCOS = 430;
    const TZ_INDIAN_COMORO = 431;
    const TZ_INDIAN_KERGUELEN = 432;
    const TZ_INDIAN_MAHE = 433;
    const TZ_INDIAN_MAYOTTE = 434;
    const TZ_INDIAN_REUNION = 435;
    const TZ_MET = 436;
    const TZ_MST = 437;
    const TZ_MST7MDT = 438;
    const TZ_PST8PDT = 439;
    const TZ_PACIFIC_APIA = 440;
    const TZ_PACIFIC_BOUGAINVILLE = 441;
    const TZ_PACIFIC_CHATHAM = 442;
    const TZ_PACIFIC_CHUUK = 443;
    const TZ_PACIFIC_EFATE = 444;
    const TZ_PACIFIC_ENDERBURY = 445;
    const TZ_PACIFIC_FAKAOFO = 446;
    const TZ_PACIFIC_FIJI = 447;
    const TZ_PACIFIC_FUNAFUTI = 448;
    const TZ_PACIFIC_GAMBIER = 449;
    const TZ_PACIFIC_GUADALCANAL = 450;
    const TZ_PACIFIC_GUAM = 451;
    const TZ_PACIFIC_KIRITIMATI = 452;
    const TZ_PACIFIC_KOSRAE = 453;
    const TZ_PACIFIC_KWAJALEIN = 454;
    const TZ_PACIFIC_MAJURO = 455;
    const TZ_PACIFIC_MARQUESAS = 456;
    const TZ_PACIFIC_MIDWAY = 457;
    const TZ_PACIFIC_NAURU = 458;
    const TZ_PACIFIC_NIUE = 459;
    const TZ_PACIFIC_NORFOLK = 460;
    const TZ_PACIFIC_NOUMEA = 461;
    const TZ_PACIFIC_PAGO_PAGO = 462;
    const TZ_PACIFIC_PALAU = 463;
    const TZ_PACIFIC_PITCAIRN = 464;
    const TZ_PACIFIC_POHNPEI = 465;
    const TZ_PACIFIC_PORT_MORESBY = 466;
    const TZ_PACIFIC_RAROTONGA = 467;
    const TZ_PACIFIC_SAIPAN = 468;
    const TZ_PACIFIC_TAHITI = 469;
    const TZ_PACIFIC_TARAWA = 470;
    const TZ_PACIFIC_TONGATAPU = 471;
    const TZ_PACIFIC_WAKE = 472;
    const TZ_PACIFIC_WALLIS = 473;
    const TZ_UTC = 474;
    const TZ_WET = 475;
    const TZ_ASIA_CALCUTTA = 476;
    const TZ_ASIA_KATMANDU = 477;
    const TZ_AMERICA_NUUK = 478;
    const TZ_NUM_TIMEZONES = 479;
}
